coreos/docs

enterprise-registry/initial-setup/index.md
Noticed this feature is also missing from the example config.
Don't worry Monday we start on working something out better than this config file.
=> Add avatar generation to example config

cluster-management/setup/flannel-config/index.md
This discusses how to configure and start flannel
on CoreOS.
=> Added flannel documentation

cluster-management/debugging/reading-the-system-log/index.md, cluster-management/setup/cluster-discovery/index.md, cluster-management/setup/flannel-config/index.md, cluster-management/setup/mounting-storage/index.md, cluster-management/setup/update-strategies/index.md
=> Spelling fixes

launching-containers/building/customizing-docker/index.md
=> launching-containers: remove unneeded unit

sdk-distributors/sdk/disk-partitions/index.md
Document the partition table and mount points.
@crawford: Can you vet this for technical accuracy?
=> sdk-distributors: document disk layout

running-coreos/cloud-providers/niftycloud/JA_JP/index.md, running-coreos/cloud-providers/niftycloud/index.md
Add English and Japanese version of NIFTY Cloud docs.
=> running-coreos: add niftycloud docs

running-coreos/platforms/virtualbox/index.md
Added document to run CoreOS on Oracle VirtualBox platform.
Depends on coreos/scripts#220
=> Added documentation to VirtualBox platform

cluster-management/setup/cluster-architectures/index.md, cluster-management/setup/cluster-discovery/index.md, cluster-management/setup/network-config-with-networkd/index.md, quickstart/index.md, running-coreos/cloud-providers/auro/index.md, running-coreos/cloud-providers/azure/index.md, running-coreos/cloud-providers/brightbox/index.md, running-coreos/cloud-providers/digitalocean/index.md, running-coreos/cloud-providers/ec2/index.md, running-coreos/cloud-providers/google-compute-engine/index.md, running-coreos/cloud-providers/niftycloud/JA_JP/index.md, running-coreos/cloud-providers/niftycloud/index.md, running-coreos/cloud-providers/rackspace/index.md, running-coreos/cloud-providers/vexxhost/index.md, running-coreos/platforms/openstack/index.md, running-coreos/platforms/vagrant/index.md
=> *: add ?size= param to discovery urls

distributed-configuration/customize-etcd-unit/index.md
Fixes https://github.com/coreos/bugs/issues/292
cc: @marineam
=> use /etc not /run for etcd dropin

running-coreos/platforms/cloudstack/index.md
Document contains instructions to deploy CoreOS instances on CloudStack installations
=> CloudStack docs for CoreOS

launching-containers/building/registry-authentication/index.md
It was not clear to me when reading the docs that the .dockercfg was generated on docker login and I spent some time trying to write my own. Hopefully this update suffices to inform the next person.
Please leave comments if not merged.
=> update Using Authentication for a Registry

quickstart/index.md
=> quickstart: fix etcd api version

cluster-management/debugging/install-debugging-tools/index.md
https://twitter.com/rosskukulinski/status/586588423483367424
=> cluster-management: add toolbox cloud-config example

launching-containers/launching/getting-started-with-systemd/index.md
Was going through documentation and was confused for a second. Made the Description a noticeable attribute, not a passing comment.
=> Made comment about Description more clear.

running-coreos/cloud-providers/interoute/index.md
Dear team,
Please can you review this PR regarding adding this doc for Interoute VDC.
Best
Dong
=> Interoute VDC documentation merge request

cluster-management/setup/configuring-date-and-timezone/index.md
timesyncd is now the default so we need to document configuring it as
well as ntpd. Some people will need to switch back to ntpd as well.
Also note that UTC is the default.
Fixes https://github.com/coreos/bugs/issues/363
=> ntp: update to cover systemd-timesyncd

cluster-management/debugging/manual-rollbacks/index.md
=> docs: punctuation fixes

running-coreos/platforms/openstack/index.md
fixed URL to config drive openstack documentation
=> Update index.md to fix broken link

running-coreos/bare-metal/booting-with-pxe/index.md, running-coreos/cloud-providers/auro/index.md, running-coreos/cloud-providers/azure/index.md, running-coreos/cloud-providers/brightbox/index.md, running-coreos/cloud-providers/digitalocean/index.md, running-coreos/cloud-providers/ec2/index.md, running-coreos/cloud-providers/ecs/index.md, running-coreos/cloud-providers/exoscale/index.md, running-coreos/cloud-providers/google-compute-engine/index.md, running-coreos/cloud-providers/niftycloud/JA_JP/index.md, running-coreos/cloud-providers/niftycloud/index.md, running-coreos/cloud-providers/rackspace/index.md, running-coreos/cloud-providers/vexxhost/index.md, running-coreos/platforms/openstack/index.md, running-coreos/platforms/vagrant/index.md
@crawford Snuck a `network-online.target` commit in here for ECS
=> running-coreos: update cloud-config for etcd2

cluster-management/setup/cluster-discovery/index.md
Add info for etcd2
cc @xiang90
=> cluster-mgmt: update discovery doc for etcd2

cluster-management/setup/switching-channels/index.md, running-coreos/bare-metal/booting-with-ipxe/index.md, running-coreos/bare-metal/installing-to-disk/index.md, running-coreos/cloud-providers/vexxhost/index.md, running-coreos/platforms/eucalyptus/index.md, running-coreos/platforms/libvirt/index.md, running-coreos/platforms/vmware/index.md
/cc @brianredbeard
/cc @robszumski
=> Fixed CoreOS release channels typos

running-coreos/platforms/libvirt/deploy_coreos_cluster.sh, running-coreos/platforms/libvirt/index.md
I've removed libvirt instance XML, added virt-install instructions and added example which shows how is it possible to run CoreOS cluster demo using libvirt.
/cc @brianredbeard
=> Updated libvirt doc

cluster-management/setup/mounting-storage/index.md, quickstart/index.md
=> Updated etcd2 port in examples and added NFS mount example

cluster-management/setup/verify-images/index.md
=> Added instruction about how to verify CoreOS images

os/booting-with-libvirt.md
=> os: update wget url

kubernetes/getting-started.md
=> kubernetes: add gettig started guide

os/booting-with-libvirt.md
=> os: match script name

fleet/launching-containers-fleet.md
=> fleet: remove front matter

os/scheduling-tasks-with-systemd-timers.md
=> Added systemd timers doc

os/using-systemd-drop-in-units.md
Have copy-pasted some text from systemd man page. Added cloud-config exmaples
=> Added systemd drop-ins doc

os/booting-on-ec2.md
=> Fixed etcd2 ports in security group rules for ec2

os/booting-with-ipxe.md, os/booting-with-libvirt.md
=> Fixed links, formatting

os/configuring-dns.md
=> os: add configuring dns document

os/booting-on-vmware.md
Users should be using the standard VMware images. This suggests that
they use the OVF image so it can be directly imported into ESXi.
=> os: update vmware guide

os/using-systemd-and-udev-rules.md
Rob, can you suggest another udev example?
=> Added udev example

os/network-config-with-networkd.md
https://github.com/coreos/docs/issues/519
/cc @robszumski
=> Added networkd debug mode instruction.

fleet/launching-containers-fleet.md
Fixing merge conflicts in https://github.com/coreos/docs/pull/496
=> fleet: explain fleet machine failure scenario

os/deploy_coreos_libvirt.sh
=> Added CHANNEL variable in deploy_coreos_libvirt.sh

os/using-environment-variables-in-systemd-units.md, os/using-systemd-drop-in-units.md
copy-pasted some info from systemd man, added coreos examples
=> Added systemd environment configuration examples

os/mounting-storage.md
Clarify language.
Adopt and apply NFS convention of "export" rather than "share".
Add refs to external docs (see rpc.statd).
=> os/mounting-storage: NFS: Refine language, add references.

os/adding-certificate-authorities.md, os/customize-etcd-unit.md, os/customizing-docker.md, os/generate-self-signed-certificates.md, os/using-environment-variables-in-systemd-units.md
/cc @robszumski #575
I'm not sure which certificates tool should we use. But I suppose we have to promote our tools. If so, @yichengq should publish etcd-ca binaries for linux/darwin
=> Added Docker TLS configuration doc

os/booting-on-ec2.md
Part of https://github.com/coreos/bugs/issues/461
=> os: add EC2 json feed

etcd/getting-started-with-etcd.md
=> Replaced 4001 etcd port with 2379

kubernetes/services.md
Possibly just a typo :-). Thanks for the awesome documentation on kubernetes services ;-)
=> kubernetes service example is actually a JSON, not YAML

os/booting-on-ec2.md, os/booting-on-vagrant.md, os/installing-to-disk.md
* Added complete example for bare-metal setup
* Added additional info for Vagrant
* Tiny fixes
/cc @robszumski
=> Fixed cloud-config examples for platforms

os/generate-self-signed-certificates.md
=> Fixed some typos and terms for cfssl doc

os/adding-certificate-authorities.md, os/booting-on-auro.md, os/booting-on-azure.md, os/booting-on-digitalocean.md, os/booting-on-ec2.md, os/booting-on-ecs.md, os/booting-on-google-compute-engine.md, os/booting-on-niftycloud-JA_JP.md, os/booting-on-niftycloud.md, os/booting-on-openstack.md, os/booting-on-rackspace.md, os/booting-on-vagrant.md, os/booting-on-vexxhost.md, os/booting-on-virtualbox.md, os/booting-on-vultr.md, os/booting-with-iso.md, os/btrfs-troubleshooting.md, os/cluster-architectures.md, os/customizing-docker.md, os/getting-started-with-docker.md, os/getting-started-with-systemd.md, os/install-debugging-tools.md, os/installing-to-disk.md, os/mounting-storage.md, os/overview-of-systemctl.md, os/quickstart.md, os/reading-the-system-log.md, os/registry-authentication.md, os/using-environment-variables-in-systemd-units.md
This inconsistency always bothers me, so this is my first pass at fixing
it.
=> *: docker -> Docker

os/network-config-with-networkd.md
=> Added info on how to configure multiple IP addresses

os/configuring-date-and-timezone.md
Fixes https://github.com/coreos/docs/issues/628.
=> os: fix cloud-configs

os/update-strategies.md
=> Updated update/reboot strategies page

etcd/etcd-live-http-to-https-migration.md
/cc @robszumski @yichengq @xiang90 
I've noticed several requests on live http->https migration. Here is it.
=> Added live http->https migration manual for etcd2

os/getting-started-with-docker.md
Fix broken links in  getting-started-with-docker.md
=> Fix broken links in getting-started-with-docker.md

os/network-config-with-networkd.md, os/reading-the-system-log.md
=> Added debug info for journald

os/generate-self-signed-certificates.md
=> Fixed links in "Generate Self Signed Certificates" doc

etcd/etcd-live-http-to-https-migration.md
Initial doc didn't use auth based on client/server certificates. Fixed.
Also info about `etcdctl` and `--no-sync` has been added.
=> Fixed etcd http->https migration, added auth flags

os/centralized-logging.md, os/reading-the-system-log.md
This is only draft. We have to wait until https://github.com/coreos/bugs/issues/919 resolved to avoid all these drop-ins/libs download/etc.
=> Added info on how to configure journald log aggregation

os/booting-on-vmware.md
=> Added VMware Workstation and Backdoor/Guestinfo notes

os/booting-on-vmware.md
@kayrus PTAL to check I didn't break any facts while rewriting.
=> os/booting-on-vmware: Polish lang/style.

os/selinux.md
- Change progression: readlink (corner failures) -> realpath (obsolescent) ->
readlink -f (desired canonicalization of symlink absolute path).
- Link the file-issue recomendation to the bugs/issues URL.
- Title Case Headings.
- Tune language/style.
- Prefix blocked cmd lines with prompt (`$`) to distinguish from cmd output.
=> os/selinux: s/realpath/readlink -f/

quay-enterprise/configure-machines.md
=> qe: Add ImagePullSecret to machine config doc

os/network-config-with-networkd.md
=> Added static route example

os/registry-authentication.md
=> docs: os: registry-authentication

os/network-config-with-networkd.md
=> Added bonding example

coreupdate/getting-started.md
Some links were pointed to the old docs.
=> coreupdate: fix dead links

os/booting-with-ipxe.md, os/booting-with-libvirt.md, os/booting-with-pxe.md, os/hosting-cloud-config-using-nginx.md, os/installing-to-disk.md
and added links to other platforms which don't support automatic IP substitution.
/cc @joshix @robszumski
=> Moved nginx sub config to a separate doc page

ignition/examples.md
Unwrap lines. Inline links. ATX headers. Typos fixed. Polish a little language. Ref #633
=> ignition/examples: Tweaks to language and format.

os/booting-on-digitalocean.md
This link was broken and probably unessecary.
#hackday
=> os: digitalocean: remove link to size.png

os/installing-to-disk.md
rename *cloud-config.yml* to *cloud-config.yaml*
=> change cloud-config extension to yaml

etcd/etcd-live-http-to-https-migration.md
Polish language. @kayrus please look over to ensure I haven't rendered anything inaccurate in the process.
(@omkensey and I will be further reworking this to merge some of his content from prosvcs.)
=> etcd/https-migration: Language rewrite (non-content).

os/booting-on-azure.md
Also this needs to be updated at https://coreos.com/os/docs/latest/
=> Change 'Azure' → 'Microsoft Azure'

STYLE.md
Remove a subheading beneath § *Command Line Grammar*
=> STYLE: Delete prolix heading.

README.md
Pull requests are a feature of GitHub, not git.
=> README: change pull request description

STYLE.md
This example will probably be excised in future but not ready to stop updating it for every fiddly little document change yet.
=> STYLE: Update example headings struct to match deleted heading

ignition/examples.md
=> ignition: fix raid example

os/deploy_coreos_libvirt.sh
=> Beautify libvirt deploy script

ignition/what-is-ignition.md
split https://github.com/coreos/ignition/pull/159 into two parts.
=> Added note about GRUB and PXE

coreupdate/on-premise-deployment.md
This question has come up a few times and was missing from our docs.
=> coreupdate: document air-gapped package management

os/customize-etcd-unit.md, os/customizing-docker.md, os/registry-authentication.md, os/update-strategies.md
=> Define drop-ins in proper way

coreupdate/on-premise-deployment.md
I replaced the wrong text in #737.
=> coreupdate: fix mistaken text replacement from #737

os/booting-on-rackspace.md
Fixes https://github.com/coreos/docs/issues/742.
=> os: add missing closing anchor tags

os/booting-on-ec2.md
I noticed this typo and removed it.
=> Remove errant "</br>" tag

os/booting-on-vmware.md, os/installing-to-disk.md
=> Added cloud-config example into VMWare, cleaned up links in bare-metal doc

os/quickstart.md
This will allow all links to work when browsed on Github
fixes https://github.com/coreos/docs/issues/756
=> docs: update quickstart links

os/booting-on-cloudstack.md
Let's use markdown instead of HTML.
=> os: clean up cloudstack docs

ignition/examples.md, ignition/network-configuration.md
=> ignition: use spaces instead of tabs for indent

etcd/etcd-live-cluster-reconfiguration.md, etcd/etcd-live-http-to-https-migration.md
=> Added etcd "disaster recovery" case

os/coreos-hardening-guide.md
fixes coreos-inc/coreos-pages#586
=> coreos-hardening-guide: Fix markdown renderer kinks

os/coreos-hardening-guide.md
related backport in coreos-inc/coreos-pages#590
=> coreos-hardening-guide: Make guide links a list

coreupdate/on-premises-deployment.md, coreupdate/updatectl-client.md, quay-enterprise/initial-setup.md
Ref coreos-inc/coreos-pages#612.
=> *: Rename files and fix strings to on-premiseS

STYLE.md
Confusion is arising over the title/heading distinction for case.
Write *Sentence case* for all titles and headings.
Perpetual incidental exception granted to:
@robszumski's visual discretion.
Priority of changing existing content: Low.
Importance of future consistency: Medium.
Modernization factor: High.
=> STYLE: Sentence case everywhere

quay-enterprise/quay-ssl.md
Fix heading hierarchy
Correct links to ref style
Light edits
=> quay-enterprise: Clarify and fix qe-ssl doc

quay-enterprise/high-availability.md
Note: I'll rebase after the georep docs are in
=> QE HA documentation

etcd/etcd-live-cluster-reconfiguration.md, etcd/etcd-live-http-to-https-migration.md, etcd/getting-started-with-etcd.md, etcd/tls-etcd-clients.md
Match downstream backport prequel coreos-inc/coreos-pages#639
=> etcd/: Update 10 rel links to crawfred style

os/booting-with-ipxe.md
Plagiarizing #796 
Reference #793 pt 2
=> os/booting-with-ipxe: Add rootfstype options

etcd/etcd-live-cluster-reconfiguration.md, etcd/etcd-live-http-to-https-migration.md, etcd/getting-started-with-etcd.md, etcd/tls-etcd-clients.md
=> Revert "etcd/: Update 10 rel links to crawfred style"

os/booting-on-eucalyptus.md, os/booting-on-openstack.md, os/booting-on-vmware.md, os/booting-on-vultr.md, os/booting-with-iso.md, os/booting-with-libvirt.md, os/booting-with-pxe.md, os/booting-with-qemu.md, os/deploy_coreos_libvirt.sh, os/notes-for-distributors.md, os/sdk-building-production-images.md, os/verify-images.md
=> Use HTTPS for OS download URLs

kubernetes/network-troubleshooting.md
Add guide to k8s network troubleshooting with toolbox on
CoreOS. Ref #802.
=> kubernetes/: Add network troubleshooting doc

os/install-debugging-tools.md
=> os/install-debugging-tools: Fix format nits

STYLE.md
Define rules for:
* CoreOS's
* on-premises
* GIFEE expansion
=> STYLE: Add specific phrase rules

os/manual-rollbacks.md
=> os/manual-rollbacks: Add channel downgrade instructions

kubernetes/network-troubleshooting.md
Ref https://github.com/coreos-inc/coreos-pages/issues/687 https://github.com/coreos-inc/coreos-pages/pull/689
=> kubernetes/network-troubleshooting: Stop liquid processing

etcd/getting-started-with-etcd.md
Ref coreos-inc/coreos-pages#695
=> etcd/getting-started: Fix API button link

os/update-strategies.md
best-effort is troublesome for a variety of resasons. We shouldn't be recommending it.
cc @mischief
=> update-strategies: remove mention of best-effort

quay-enterprise/clair.md
Upstream the changes in https://github.com/coreos-inc/tectonic-pages/pull/180
=> quay-enterprise/clair.md: Upstream postgres conf hotfix

quay-enterprise/bitbucket-app.md
Add some level 2 headings to populate the sidebar thumb index on
tectonic.com.
Ref backport of same in https://github.com/coreos-inc/tectonic-pages/pull/188
=> quay-enterprise/bitbucket-app: Add headings for sidebar nav

os/registry-authentication.md
Clear up the file path from https://github.com/coreos/docs/pull/834
=> os: make file path clear in registry auth

os/adding-users.md
=> os: correct ignition example for adding users

quay-enterprise/github-app.md
Add headings to address coreos/docs#848.
Slight edits for readibility.
Add an intro "what is this doc" sentence.
=> quay-enterprise/github-app: Add headings, slight rewrite

os/adding-users.md
Change the doc to match what is coded in ignition.
cc: @crawford
=> adding-users: Fix groups

os/configuring-date-and-timezone.md
Ignition file creation need to be under "storage" object https://coreos.com/ignition/docs/latest/examples.html
=> Update ignition examples

flannel/flannel-config.md
Update flannel docs to correspond to how flannel is launched in
CoreOS 1097 and newer.
=> flannel: update docs to use rkt

os/booting-with-pxe.md
With this change users don't have to extract the CoreOS image but can simply add their additions as a second initramfs. Much less effort.
See http://www.syslinux.org/wiki/index.php?title=SYSLINUX#INITRD_initrd_file for background info.
=> Put initrd on separate line to support multiple initramfs

os/booting-with-pxe.md
=> os/booting-with-pxe: Make inline link ref-style

upgrade-quay-enterprise.md
Add new document from @ErnestG4 and Ivan with steps to upgrade QE.
=> quay-enterprise/upgrade: Document QE upgrade process

os/using-environment-variables-in-systemd-units.md
=> Added system wide env vars example

os/collecting-crash-logs.md
Helps address https://github.com/coreos/bugs/issues/477.
=> os: add pstore documentation

os/generate-self-signed-certificates.md
=> Updated cfssl to 1.2

os/generate-self-signed-certificates.md
=> Updated cfssl to 1.2 (part 2)

quay-enterprise/prometheus.md
=> Add documentation for using Prometheus with Quay Enterprise

flannel/flannel-config.md
applies upstream side of hot fix in https://github.com/coreos-inc/coreos-pages/pull/914
=> flannel/flannel-config.md: Fix broken link to flanneld.service

etcd/getting-started-with-etcd.md
Leader is the preferred and/or more correct term (within the etcd
project, in the specific context of elections, and in the community at
large) - let's try be a little more consistent about it.
=> etcd: master -> leader

os/other-settings.md
=> os/other-settings: document preserving boot messages

kubernetes/cluster-dump-restore.md
@robszumski @joshix still need to test this to make sure the instructions work verbatim, but otherwise ready to review.
\cc @philips
=> kubernetes: cluster dump/restore instructions

quay-enterprise/tectonic/files/quay-enterprise-app-rc.yml, quay-enterprise/tectonic/files/quay-enterprise-config-secret.yml, quay-enterprise/tectonic/files/quay-enterprise-namespace.yml, quay-enterprise/tectonic/files/quay-enterprise-redis.yml, quay-enterprise/tectonic/files/quay-enterprise-service-loadbalancer.yml, quay-enterprise/tectonic/files/quay-enterprise-service-nodeport.yml, quay-enterprise/tectonic/index.md
Moving the QE on Tectonic docs from their old location to here, in order to keep them all in the same place.
=> qe: add QE on Tectonic installation guides

os/installing-to-disk.md
User on IRC:
> alright yeah, that was it. used a bigger card and no problems. maybe "you'll get this cryptic error message if the device is too small" should be added to those docs? I feel like installing a server OS on 4 GB probably isn't that uncommon.
=> os: add device size requirements

os/kernel-modules.md
=> os/kernel-modules: document building custom modules

os/booting-on-niftycloud.md
Fixing Link for "available in Japanese"
=> available in japanese 404 fix

quay-enterprise/insert-custom-cert.md
add certificate examples, show .pem in container
=> quay-enterprise: doc on inserting certificate in qe container

kubernetes/pods.md
=> kubernetes: Fix typo

quay-enterprise/ldap-setup.md
Customer asked if Quay will search for OUs nested under top OUs. Based on my testing, adding findings in the tips section
=> Docs: QE LDAP

os/booting-on-vmware.md
Missed a couple in 60ef69df44101b82e96db9a479397d64d81c4e84.
=> os: rename coreos to container linux

os/sdk-modifying-coreos.md
=> os/sdk: document using cork as an option

flannel/flannel-config.md
From https://github.com/coreos/bugs/issues/1756.
=> flannel: update docker_opts path

os/booting-on-azure.md, os/booting-on-digitalocean.md, os/booting-on-ec2.md, os/booting-on-ecs.md, os/booting-on-google-compute-engine.md, os/booting-on-packet.md, os/booting-on-vmware.md, os/booting-with-ipxe.md, os/booting-with-pxe.md, os/booting-with-qemu.md
=> os: update official oems to use ignition

fleet/launching-containers-fleet.md
=> fleet: Add fleet deprecation notice.

kubernetes/daemon-sets-vs-global-units.md
This is a work in progress. Feedback and discussion encouraged.
References documentation needed to transition toward Kubernetes from fleet.
cc: @joshix
=> Kubernetes Daemon Sets vs fleet Global unit

kubernetes/affinity.md
This is a work in progress. Feedback and discussion encouraged.
References documentation needed to transition toward Kubernetes from fleet.
cc: @joshix
=> Affinity and anti-affinity in Kubernetes vs fleet

os/booting-on-interoute.md
This is an update for booting on Interoute VDC in its current configuration.
=> Update booting on interoute

kubernetes/service-dependencies.md
This is a work in progress. Feedback and discussion encouraged.
References documentation needed to transition toward Kubernetes from fleet.
cc: @joshix
=> Kubernetes init containers vs fleet ExecPre

os/using-environment-variables-in-systemd-units.md
Fixes https://github.com/coreos/docs/issues/998
=> os: add missing example of file contents

STYLE.md
I have added a new section to explain style-related information to format code blocks in a document.
https://www.pivotaltracker.com/n/projects/1946201/stories/140636361
=> STYLE: added a section for code block - 140636361

os/booting-on-openstack.md
Feedback from a customer that public shouldn't really be the default.
=> os: booting-on-openstack: fix the public flag

os/integrations.md, os/production-users.md
Production-users and Integrations pages, per the request from @philips
=> Added production users and integrations pages

STYLE.md
Proposed. List of projects with lower case rule can probably be lengthened.
Eventually want to simplify this rule to be "Project names are proper nouns." Currently proposing we write them with initial capitals when beginning a sentence. Baby steps.
=> STYLE: Update GIFEE expansion. Add capitalization rules for project names

etcd/getting-started-with-etcd.md
Fix https://github.com/coreos/etcd/issues/7436.
Also address https://github.com/coreos/docs/issues/989.
/cc @euank @crawford @xiang90
=> etcd: 'etcd-member.service' in Container Linux

etcd/getting-started-with-etcd.md
=> etcd: fix invalid json

flannel/flannel-config.md
- Drop note about ancient CL versions
- Fix rendering of Container Linux config
=> flannel: Minor fixups

os/manual-rollbacks.md
https://github.com/coreos/docs/pull/1026 has lost its fork. Creating this PR to address those issues.
=> Docs: Add note arbitrary rollback unsupported

os/coreos-hardening-guide.md
=> os: update links in coreos-hardening-guide

quay-enterprise/build-support.md, quay-enterprise/initial-setup.md, quay-enterprise/insert-custom-cert.md, quay-enterprise/tectonic/files/quay-enterprise-app-rc.yml
=> quay: bump version tags v2.3.0 -> v2.3.1

os/booting-on-ec2.md
Missed in #1060 
And I force-pushed too slowly to fix the elif typo and the 2 other places, whoops.
=> os/ec2: update link for china console

os/booting-on-ec2.md
Hopefully.  I don't think I can easily test this since I can't modify coreos-pages PRs to rerun the test.
=> os/ec2: fix syntax errors

os/provisioning.md
=> docs: 1st draft editorial pass

etcd/getting-started-with-etcd.md, etcd/os-faq.md
There's a few mis-conceptions about etcd. This document clarifies some of that confusion.
Future work:
- Link to this document prominently in:
- etcd's landing page
- etcd's docs landing page
- etcd's getting started page
=> etcd: os faq

quay-enterprise/build-support.md, quay-enterprise/initial-setup.md, quay-enterprise/insert-custom-cert.md, quay-enterprise/tectonic/files/quay-enterprise-app-rc.yml
Version bump for Quay Enterprise.
=> quay: version bump.

os/cluster-architectures.md
This needs to be massively updated. This is my first attempt at that. It's admittedly rough around the edges, but it's transitioned away from cloud-config to Container Linux config, and all instances of fleet are scrubbed.
Please give me some feedback. I need it.
=> os: cluster-architectures update.

os/cluster-architectures.md, os/provisioning.md
as opposed to one broken one and one missing one.
xref https://github.com/coreos/docs/issues/1068
cc @crawford @dgonyeo if there's a better link to use or place to put it.
=> os: include a couple working ct download links

os/production-users.md
The idea to add myself to the list came from a answer of a tweet by @pgburt https://twitter.com/ThatMightBePaul/status/875055439506964482
I hope with this entry I can make the list grow further ;)
=> Added myself as a person, who uses Container Linux for my projects

os/installing-to-disk.md
https://github.com/coreos/init/pull/241
https://github.com/coreos/init/pull/242
=> os/installing-to-disk: Update for coreos-install changes

os/booting-on-virtualbox.md
when virtual machine use NAT we need to do additional port forwarding steps
=> add NAT port forwarding notes

quay-enterprise/custom-cert-kube-apps.md
Need this document to release QE v2.4.0
=> quay-enterprise: add doc on using helm registry with self-signed cert

os/customizing-sshd.md
See individual commit comments.
cc @crawford and @kbrwn
=> sshd: update de-socket-activationizing instructions to be a little nicer

quay-enterprise/high-availability.md
typo fix in high-availability.md
=> quay-enterprise: fix typo in high-availability.md

etcd/etcd-live-cluster-reconfiguration.md
Ref: https://github.com/coreos/docs/pull/1132
=> etcd/etcd-live-cluster-reconfiguration.md: Fix the doc as per the final comments in pull 1132

os/root-filesystem-placement.md, os/sdk-tips-and-tricks.md
Depends on:
https://github.com/coreos/mantle/pull/690
https://github.com/coreos/mantle/pull/689
https://github.com/coreos/bootengine/pull/132
cc: @bgilbert
=> os: add docs for having root on raid

os/booting-with-iso.md
https://github.com/coreos/bugs/issues/2150
=> os/booting-with-iso: Document BIOS boot requirement

os/adding-swap.md
The previous ones didn't use systemd `.swap` units, which are the
appropriate tool for this.
Note: do not merge until I've tested this, this is untested.
cc @dgonyeo @zbwright as some possible reviewers
=> os/swap: update instructions

torcx/troubleshooting.md
=> torcx: add troubleshooting guide

os/booting-with-libvirt.md
The downloaded file is **coreos\_production\_qemu\_image.img.bz2**
=> Fix filename

os/quickstart.md
Some trivial cleanup. Broader rewrite still pending (#1126 )
=> os/quickstart: update dead links

os/notes-for-distributors.md, os/sdk-building-production-images.md, os/sdk-tips-and-tricks.md
=> os: Developer documentation updates

etcd/etcd-live-cluster-reconfiguration.md
This was preventing the markdown from rendering properly.
=> etcd: fix code-fence formatting

os/booting-with-pxe.md, os/notes-for-distributors.md
=> os: update for Ignition system dir support

quay-enterprise/quay-tectonic-identity.md
This doc has been tested by myself and another support engineer.
=> adds doc on configuring quay-enterprise with tectonic-identity

os/sdk-modifying-coreos.md
=> os/sdk-modifying-coreos: bump mantle version

os/sdk-modifying-coreos.md
These are a couple things I stumbled upon during my first SDK build:
* How to verify you are in the sdk chroot
* How to exit the sdk chroot
* How to enable KVM support in BIOS to allow booting
cc @bgilbert @zbwright
=> Small improvements for SDK newbies

os/sdk-modifying-coreos.md
* Fixing ordering of sdk chroot steps
* in-lining sudo note for readability
cc @bgilbert
=> Fixing order of SDK steps

quay-enterprise/schema.md
=> [quay] add schema config for Quay Enterprise

os/sdk-modifying-coreos.md
I've added some facts that I found useful when booting the vm, in brief they are:
1. path to find shell script to start the vm,
2. ways to login,
3. how to determine if virtualization is enabled.
=> os: document qemu-booting custom builds

os/booting-on-google-compute-engine.md
Depends on https://github.com/coreos/coreos-overlay/pull/3319
=> os/booting...gce: Add section on OS Login

os/other-settings.md
updated PR for: https://github.com/coreos/docs/pull/1240
=> os: add Ignition example for grub.cfg

ignition/metadata.md
https://github.com/coreos/coreos-metadata/pull/182
=> ignition: link to coreos-metadata legacy-mode docs
