cluster-management/setup/mounting-storage/index.md

The mount being done in the example is just a regular device mount, not a bind mount. Remove "bind" from the description.

Don't call it a "bind mount" when it's not

---

running-coreos/cloud-providers/ecs/index.md

Up for review now but I need to wait for my personal account to get added to the ECS preview to test the global unit.
cc: @crawford

running-coreos: expand how to use ECS with new and existing clusters

---

launching-containers/launching/getting-started-with-systemd/index.md

A small addition to explain why separate `ExecStartPre`, `ExecStart`, and `ExecStop` options are preferred to a single `ExecStart` using `docker run --rm`.
Closes #418.

Explain why docker run --rm isn't used for ExecStart.

---

running-coreos/bare-metal/installing-to-disk/index.md

Added missing params `-b` and `-v`
cc: @marineam

running-coreos: update install script options

---

cluster-management/setup/cluster-architectures/index.md

This syntax was changed in `fleet` 0.9.0 - unix socket paths must now be prepended with `file://`, or else they don't work.

Update FLEETCTL_ENDPOINT syntax for unix sockets

---

running-coreos/platforms/openstack/index.md

running-coreos: use standard channel tabs on Openstack

---

running-coreos/platforms/virtualbox/index.md

Cleans up work done in https://github.com/coreos/docs/pull/146
- adds the standard channel tabs
- replaces the hardcoded 298 version number with "stable". I retained a note that specific versions can also be referenced.
- minor fix for heading capitalization
cc: @marineam

Virtualbox: Add channel tabs and misc cleanup

---

running-coreos/cloud-providers/vultr/index.md

1. **Install to disk rather than RAM.** The Vultr page currently explains how to install to RAM, which I believe is unique among the "cloud provider" pages. I can't imagine why one would do this on a cloud server. I can only assume it was done that way because it was the simplest possible installation at the time, but Vultr now provides their own CoreOS image so that is no longer the case.
2. **Use custom `cloud-config`.** Now that Vultr provides a CoreOS image, the only use case for a custom iso is to provide a custom `cloud-config`.
3. **Use Vultr's "Startup Scripts" feature to provide the iPXE.** This feature has been added since the docs and makes the process a lot simpler.
4. **Moved "Cloud Config" above "Choosing a Channel".** You need to know the url to your `cloud-config` before …

Update Vultr documentation.

---

launching-containers/building/registry-authentication/index.md

Got stung by this when trying to add more than one parameter here. See
https://github.com/coreos/coreos-overlay/issues/1052

Moved quote in Environment specification

---

cluster-management/setup/cluster-architectures/index.md

If you leave locksmith alone, and leave etcd running then your reboot-strategy gets all out of sync due to locksmith only talking to local etcd

added locksmith directive to example cloud-config

---

cluster-management/setup/cluster-discovery/index.md

The unquoted/unescaped question mark breaks this command. Not sure if you guys prefer escaping or quoting, but I chose quoting.

fix typo in curl command

---

quickstart/index.md

Fixes typo in the initial size comment when discussing the etcd discovery URL.

Fix typo in initial size comment

---

cluster-management/setup/flannel-config/index.md

In addition to the change requested in https://github.com/coreos/coreos-vagrant/pull/214, the documentation could explain how to make sure flannel uses the correct network interface on Vagrant.
/cc @eyakubovich

flannel: instructions for Vagrant

---

cluster-management/setup/flannel-config/index.md

Missing line break between embedded snipped and previous paragraph.  This is what this renders like outside of github:

Fix markdown

---

running-coreos/cloud-providers/niftycloud/JA_JP/index.md
running-coreos/cloud-providers/niftycloud/index.md

Fixes following issues:
* All image names are `Alpha`.
* Missing `-q POST` option.

running-coreos: fixes commands in niftycloud docs

---

sdk-distributors/sdk/modifying-coreos/index.md

depot_tools have never been required, the stand-alone repo script is all
you need. Also stick with the default repo upstream instead of
ChromiumOS's repo mirror.

sdk: simplify initial repo setup procedure

---

quickstart/index.md

The busybox container in the examples is not an actual Ubuntu installation; this change updates the text to reflect this.

Correct 'Ubuntu' to 'minimal busybox'

---

sdk-distributors/sdk/building-development-images/index.md

The description of running devserver for updates was nearly a year out
of date. Fix and clarify things a bit.

sdk: update documentation on running devserver

---

cluster-management/setup/configuring-date-and-timezone/index.md

The ntpd service is enabled in /usr instead of /etc and therefore
systemd always reports it as "disabled". Also we should not be telling
users to use the generic pool, ntp.org expects us to use our own coreos
pool.

ntp: report 'ntpd' as disabled and use coreos ntp.org pool

---

running-coreos/cloud-providers/ec2/index.md

Be specific here that two rules need to be created for users unfamiliar
with how "port range" works in security groups.
Fixes #453

ec2: Clarify that two exemptions are needed

---

cluster-management/setup/flannel-config/index.md

I believe Item 5 in the sequence of events in the flannel-config should be /run/flannel_docker_opts.env according to the flanneld.service file at https://github.com/coreos/coreos-overlay/blob/master/app-admin/flannel/files/flanneld.service and to match up with the filename in Item 7 in the same sequence.

Correct env file name

---

cluster-management/debugging/install-debugging-tools/index.md

In order for a user to use toolbox they need to be in the sudo and docker group.
See [toolbox#Advanced Usage](https://github.com/coreos/toolbox#advanced-usage) for inspiration.

Fix example command in debugging tools docs

---

running-coreos/cloud-providers/ec2/index.md

This fixes the URL for gov-cloud.

ec2 docs: update to use correct url for gov cloud

---

running-coreos/cloud-providers/exoscale/index.md

A detailed section on the cloud-config chapter about modifying the contents of cloud-config for an instance that was already created.

modifying cloud-config after launch on Exoscale

---

launching-containers/launching/launching-containers-fleet/index.md

This was a reference to older behavior that is now incorrect.

docs: don't submit template units

---

cluster-management/setup/cluster-architectures/index.md

The next step is to introduce proxy into the central service machines setup and simplify fleet initial configuration.

cluster-arch: switch to etcd2 service

---

running-coreos/cloud-providers/ecs/index.md

Prevents the ECS Agent registering as a brand new container instance every time the agent or host is rebooted.

Store ECS Agent state on the host

---

cluster-management/setup/cluster-discovery/index.md
running-coreos/cloud-providers/auro/index.md
running-coreos/cloud-providers/azure/index.md
running-coreos/cloud-providers/brightbox/index.md
running-coreos/cloud-providers/digitalocean/index.md
running-coreos/cloud-providers/ec2/index.md
running-coreos/cloud-providers/exoscale/index.md
running-coreos/cloud-providers/google-compute-engine/index.md
running-coreos/cloud-providers/niftycloud/JA_JP/index.md
running-coreos/cloud-providers/niftycloud/index.md
running-coreos/cloud-providers/rackspace/index.md
running-coreos/cloud-providers/vexxhost/index.md
running-coreos/platforms/openstack/index.md
running-coreos/platforms/vagrant/index.md

It really only makes sense to expose the legacy client port since new
clusters will all use the new server port to communicate.

docs: only expose the new etcd server port

---

cluster-management/setup/mounting-storage/index.md

Occasionally for some reason ephemeral block devices seem to take a little while to become available.
This fixes it.

Fix race condition with device availability

---

os/configuring-date-and-timezone.md

This PR aims to clarify the date/time/NTP configuration doc. #533 requests that “ntpd example should stop/mask timesyncd”. In fact the existing example did so, but was placed far away from the example describing configuration of ntpd.
* Segregated timesyncd and ntpd things in two discrete sections (533 bullet 1)
* Added restart or reload step to ntp configuration shell examples (533 bullet 2)
* Ntpd example more prominently shows/explains `mask` of stopped service. (533 bullet 3)
* Ordered topics from most to least common case.
* Moved Recommended settings close to their resp. topics so we don't say, e.g., "how to change timezone [...] oh btw don't change timezone"
* Applied basic conventions for writing `verbatim text`, `man(1)` refs. Distinguished cmd lines from stdout & file contents …

Refactor os/configuring-date-and-timezone.md to fix #533.

---

os/booting-on-packet.md

A continuation of https://github.com/coreos/docs/pull/561. Just making the format of the `curl` command a bit nicer (no escapes, consistent capitalization, etc).

Better formatting of Packet curl command

---

os/booting-on-packet.md

This PR comes from a suggestion here: https://github.com/coreos/docs/pull/562#discussion_r37026256, and just adds an example of how to specify cloud config using the Packet API.
Thanks!

Adding docs for Packet userdata

---

fleet/launching-containers-fleet.md

Removed extra '+' signs in the new documentation section, possibly due to a merge conflict.

fleet: Fixed failure scenario documentation

---

os/configuring-date-and-timezone.md

Update quoted `timedatectl` output to match that of recent systemd versions: `s/Ntp enabled/Network time on/`.
Update dates in quoted `timedatectl` output for freshness.
Supersedes #572 to tidy commit history.

[2nd] os/config-datetime: timedatectl output sync

---

enterprise-registry/mysql-container.md

fixes https://twitter.com/emeacham/status/638791348460605440
@coreoslinux https://coreos.com/products/enterprise-registry/docs/latest/mysql-container.html … needs updated; the link to the .sh file needs "mysql-container" removed from it.
cc: @josephschorr

enterprise-registry: fix script url

---

kubernetes/replication-controller.md
kubernetes/services.md

services.md: fixed a misspelling, shortened a long sentence, and inserted a missing word
replication-controller.md: changed A and B to 1 and 2, since those are the versions used in the accompanying images.

A handful of corrections in the Kubernetes docs

---

golang/.godir
golang/Dockerfile
golang/README.md
golang/build
golang/cover
golang/godep.md
golang/test

We were previously hosting those internally, but as the vast majority of
CoreOS projects are developed in the open, we should share them and have
them publicly referenceable for anyone working on CoreOS projects.

*: add our golang style and development guidelines

---

os/coreos-hardening-guide.md

Many people have asked for best practices for hardening CoreOS. This
documents some of the basic practices to check out when considering
CoreOS.

docs/os: add hardening guide for CoreOS

---

os/mounting-storage.md

-Rewrite mounting-storage guide to incorporate the mention of unit file location without repeating it in each section
-Summarize the mount unit concept first, then get specific
-Pending review by @kayrus and @robszumski, this PR supersedes #620

docs/os/mounting-storage: mount unit file location (Supersede #620)

---

os/registry-authentication.md

Projects like https://github.com/coreos/coreos-vagrant YAML.load and YAML.dump the cloud-config which changes octal 0644 to decimal 420, which is inconvenient if you prefer configs consistently use the same radix.

Change file permission to '0644'

---

os/booting-with-qemu.md

We do this for PXE, do it for QEMU too: https://coreos.com/os/docs/latest/booting-with-pxe.html

os: booting-with-qemu: add instructions for gpg verify

---

os/booting-on-ecs.md

This change makes sure that the new CloudWatch Metrics[1] get reported correctly. Also, the old version of the unit file was missing some flag / switches the ec-agent docs have.[2] This will bring the ECS docs and the CoreOS example inline.
[1] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html
[2] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

Correcting the ECS Agent systemd unit file.

---

os/adding-certificate-authorities.md

Add info about .pem extension, explicate a little about the update-ca-certs
script. Fixes #630.

os/adding-CAs: Fix broken link to the generating self-signed-ssl doc.

---

os/adding-certificate-authorities.md

Add links to the auth'd-registry doc, and to the `--insecure-registry`
section therein. Fixes https://github.com/coreos/docs/issues/648.

os/adding-CAs: Add links to auth'd registry doc.

---

os/selinux.md

`readlink` didn't provide proper result when you are inside depth > 2 path.

Fixed CLI for SElinux doc

---

os/selinux.md

/usr is read-only, so semodule can't rebuild the policy database. Update
the instructions so the policy store is copied to a writable filesystem

Fix SELinux debug instructions

---

os/selinux.md

Eliminate the bullet points per step that were unlike other docs.
Minimally explicate the commands we're running.
Prefix all cmd lines with the prompt `$` to distinguish I from O.
(Finishes up what started in #661, #665, and #666.)

os/selinux: Make more consistent with other docs; explain cmds.

---

os/booting-with-qemu.md

If you're going to decompress an image, you need to specify the bz2 file it is from as the filename argument, not the image name.

Correct booting-with-qemu.md bzip2 command

---

os/booting-on-cloudca.md

Newline seperation of fenced code blocks. Fixes #699.

os/booting-on-cloudca: Add newline to fix coreos.com rendering

---

README.md
STYLE.md

~~Add a `style/` directory.~~
Add STYLE.md guide to conventions and standards. Beginning with headings.
Addresses https://github.com/coreos-inc/coreos-pages/issues/324

Begin style guide: Document conventions

---

os/mounting-storage.md

After few weeks with btfrs partition for /var/lib/docker I ran into the "No Space Left on Device" btrfs problem mentioned here : https://coreos.com/os/docs/latest/btrfs-troubleshooting.html
This page says "Btrfs is still supported and works with the latest CoreOS releases and Docker, but we recommend using ext4." 
mounting-storage.html shows an example with a btrfs partition for /var/lib/docker, increasing the chance to provoke the "No Space Left on Device" btrfs problem. It might prevent the problem to not suggest btrfs in this case.

suggest ext4 instead of btrfs for docker partition

---

README.md

Adds a description of the desired format for coreos/docs commit
messages beneath the "Contributing" heading. Fixes #713.

README: Add commit message convention

---

CONTRIBUTING.md
README.md

Add a discrete file with contribution guidelines to satisfy
GitHub automation. Fixes #715.

CONTRIBUTING: Add a CONTRIBUTING file

---

os/sdk-modifying-coreos.md

Continuing on and superseding #595, add instructions for arm64-usr target,
with headings to clearly indicate the context switches for an arm64 build.
Attempt to dispose of the aarch64/arm64 synonyms with an explanation.

os/sdk/modifying: Add and clarify instructions for arm64

---

os/update-strategies.md

If `locksmithd` is running it complains constantly:
```
Jan 04 12:34:09 dev112-43 systemd[1]: Started Cluster reboot manager.
Jan 04 12:34:09 dev112-43 locksmithd[26936]: Cannot get update engine status: The name com.coreos.update1 was not provided by any .service files
Jan 04 12:34:09 dev112-43 systemd[1]: locksmithd.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 12:34:09 dev112-43 systemd[1]: locksmithd.service: Unit entered failed state.
Jan 04 12:34:09 dev112-43 systemd[1]: locksmithd.service: Failed with result 'exit-code'.
Jan 04 12:34:19 dev112-43 systemd[1]: locksmithd.service: Service hold-off time over, scheduling restart.
Jan 04 12:34:19 dev112-43 systemd[1]: Stopped Cluster reboot manager.
```

Disable locksmithd when you disable update-engine to avoid errors in journal

---

fleet/launching-containers-fleet.md
os/getting-started-with-systemd.md
os/quickstart.md
os/registry-authentication.md
os/using-environment-variables-in-systemd-units.md

When you don't use `trap`, `bash`/`sh` doesn't catch TERM signal which `docker stop` sends.
This causes `docker stop` timeout and then `docker kill`.
/cc @robszumski @joshix 
steps to reproduce with the Ubuntu container + bash (this example doesn't handle INT):
* `docker run -ti --rm ubuntu /bin/bash -c "while true; do echo hello world; sleep 1; done"`
* try to type `Ctrl+C`
or this busybox example doesn't handle TERM:
* `docker run -ti --name busybox --rm busybox /bin/sh -c "while true; do echo hello world; sleep 1; done"`
* Then in another window to run `docker stop busybox` it will timeout, then docker will kill it.
Both examples with the `trap 'exit 0' INT TERM;` work fine.

Added "trap" into docker "while" loop examples

---

os/booting-on-digitalocean.md

Adopt @robszumski's version of changes suggested by @kevinsimper
to warn digital ocean users about implications of "private"
networking in the DO context.
Supersedes #724. Fixes #718.

os/booting-on-digitalocean: Warn about "private" networking

---

STYLE.md

Tiny nit has been bugging me for a while. This model
headings structure is probably going the way of the
dodo soon.

STYLE: Fix model heading to sentence case

---

os/booting-on-ec2.md
os/booting-on-vagrant.md
os/booting-with-libvirt.md
os/booting-with-pxe.md
os/booting-with-qemu.md
os/quickstart.md

Repair markdown links that were using the removed external
reference links jekyll plugin.
Related to ~~and should merge along with~~ coreos-inc/coreos-pages#440.
(not necessary to merge simultaneously with the related, larger changes in the existing site (440), but the two should go fairly close together, logically)

os/: Fix links that were externally declared

---

os/mounting-storage.md

The mount unit didn't Require/Wants docker.service, so the After clause has no
effect. It's a bit more robust to use the drop-in anyway.
Fixes https://github.com/coreos/bugs/issues/1088.

os: correct external storage config

---

os/booting-on-google-compute-engine.md

I believe that all new accounts have billing enabled, so we can remove that language.

os/gce: add free trial link

---

os/booting-on-google-compute-engine.md

developers. redirects to cloud.google.com. Use the newer link.

os/gce: Update quickstart link

---

os/manual-rollbacks.md

USR-A should be mount on /usr not /mnt

Modify wrong description of mount point 

---

os/booting-on-vultr.md

Not sure why these were pointing to Rackspace IDs, since its referencing the normal image release list.

os: fix Vultr channel version references

---

etcd/etcd-live-cluster-reconfiguration.md

Cleanup edits/rewrite to the entire live-reconf document.
Incremental; second person not entirely removed and can still
stand to be clarified further (with procedure testing) in some
sections.

etcd/live-reconfiguration: Clean up style, language atop #749

---

os/cluster-discovery.md

Stop recommending using the public discovery service for anything but
bootstrap. Don't reconfigure a cluster with public discovery.
Fixes coreos/docs#755, fixes coreos/etcd#4568, fixes coreos/docs#739.

os/cluster-discovery: Update cluster reconfiguration info for later etcd

---

os/sdk-modifying-coreos.md

Add a sub section for installing binfmt support on Debian.
Remove the manual grub emerge section, which is now done
automatically by the scripts.

sdk-modifying-coreos: Update arm64 info

---

os/booting-on-vmware.md

Sorry for Nit, but VMware is spelled with lower-case "w"

Nit: Fixing VMware spelling

---

os/booting-on-vmware.md

As a newbie to CoreOS (but a 30 year veteran to unix and a 2 year Docker user), the instructions were somewhat confusing when trying to spinup CoreOS on VMware Fusino 8.1 (the latest version).  After playing around for a few hours, I got it working.  This is an attempt to make it easier for users in the same situation.

Update instructions for newer version of VMWare Fusion

---

os/customizing-sshd.md

I tested this and it works for me on 1010.1.0 and seems to have been the
intention based on the discussion here: https://github.com/coreos/bugs/issues/426
cc @joshix @crawford

os: fix instructions for customizing sshd

---

os/booting-with-pxe.md

Fixes https://github.com/coreos/docs/issues/793.

os: re-add rootfstype command line flag

---

os/customizing-sshd.md

Adds an additional section to Customizing the SSH Daemon doc.
This provides a work-around for: https://github.com/coreos/bugs/issues/966 which was recently brought up on the mailing list. 
Unit is based off of this gist from phillips: https://gist.github.com/philips/7e9f7d5990c9e3db65be22943308771d

os: add instructions to disable socket-activated sshd

---

os/install-debugging-tools.md

Describe how toolbox creates and runs the container filesystem, and what
that means for persistence of the container.

docs: Add description of how toolbox runs

---

quay-enterprise/build-support.md
quay-enterprise/clair.md
quay-enterprise/initial-setup.md

Upstream of bulk of https://github.com/coreos-inc/tectonic-pages/pull/187,
minus the change in coreos-inc/tectonic repo (in https://github.com/coreos-inc/tectonic/pull/229).

quay-enterprise/: Update pulls with image version tags

---

os/network-config-with-networkd.md

Ignition debug drop-in was mislabeled with a Cloud-Config heading. Changed to the correct "Enable debugging through Ignition".

os/network-config-with-networkd.md - Fix heading for Ignition debug option.

---

quay-enterprise/build-support.md
quay-enterprise/initial-setup.md

Ref https://github.com/coreos-inc/tectonic-pages/pull/211
Proposed TODO: These should be version "latest", as they are in the
quay-enterprise yaml owned by the tectonic team, see
https://github.com/coreos-inc/tectonic/commit/4f15f8c58321ddf433ceb6ba3838875db2735353#diff-98914fd9e6d06eab312a20550c5fe2df

quay-enterprise/: Update quay container version to current 1.16.3

---

os/registry-authentication.md

Current stable CoreOS works with this configuration. I also changed the
permissions of the config file to reflect what docker itself uses.
Proof
You can see that the config tests are expecting this format. I couldn't
find any better proof. I tested it myself with CoreOS stable (1068.8.0)
and it works.
https://github.com/docker/docker/blob/v1.10.3/cliconfig/config_test.go#L262

Update auths of docker config

---

os/nginx-host-cloud-config.md

Fixes the broken nginx config reported [here](https://groups.google.com/forum/#!topic/coreos-user/Sa73kaNlpME) and https://github.com/coreos/docs/issues/872
Previously, the `$` was getting interpreted by nginx.
cc: @chancez

os: nginx config now escapes $ in variables

---

etcd/tls-etcd-clients.md

ETCD_SSL_DIR isn't documented in the coreos docs, but probably should be.

Adding documentation about ETCD_SSL_DIR

---

os/selinux.md

removed the second 
"$ rm /etc/audit/rules.d/99-default.rules" line

SELinux Docs: copy & paste mistake

---

os/booting-with-libvirt.md

This is a rebased version of #414.
@ibukanov:
> With SElinux in enforcing mode it is necessary to label manually the config dir on the host so CoreOS can access it.
#414 was given a +1 by @marineam.  Let's merge it this time!

Rebased config dir and SELinux

---

os/network-config-with-networkd.md

Document the systemd-approved way to disable IPv6 since the upstream fix for coreos/bugs#1419 was closed.

os/network-config-with-networkd: add supported ways to disable IPv6

---

os/network-config-with-networkd.md

Based on user feedback on this thread: https://groups.google.com/d/msg/coreos-user/OaOX8AuoQCE/w3qVCTqCAQAJ

network-config-with-networkd: change MIIMonitorSec to 1

---

quay-enterprise/generate-signing-keys.sh

The email used in generating a public signing key should be pulled from aci-signing-key-batch.txt
Changed to pull from the second entry of the row with a first entry of "Name-Email:" in aci-signing-key-batch.txt.

Fix email in key generation script

---

os/adding-users.md

Visudo on CoreOS requires the file be specified or an error is thrown.
Issue: https://github.com/coreos/bugs/issues/1617

os: add section on visudo usage to adding-users doc

---

os/booting-on-google-compute-engine.md

**Commit details**
This commit removes the need to maintain exact versions or dates for
coreos in the docs example of creating gcloud compute instances.
Motivated by an out of date (or deprecated) version preventing the
docs example from running.
The GCP SDK supports image resolution via `--image-family` and
`--image-project` flags as an alternative to the `--image` flag. Using
`--image-family`, the latest non-deprecated image will be used. Rather
than `--image` where the full name must be used. Details on the flags
available at
https://cloud.google.com/sdk/gcloud/reference/compute/instances/create.
**Broken doc example**
At the time of this writing, `gcloud compute instances create` command shows:
Here the value for `--image` is …

os/booting-on-gce: use --image-family instead of --image

---

quay-enterprise/quay-enterprise-2.md

Emphasis on using the management panel over the manual option by listing it first in the doc.
Adds an example of what the config dir needs to look like before the QE container is started.

qe: revamp section on manually adding license file

---

STYLE.md

Stating the instruction _then_ clarifying why, not the other way around.
Origin story: I misread the original paragraph and spread the incorrect interpretation. I think this'll help future versions of me.
@joshix

STYLE.md: 'one paragraph per line' clarification

---

etcd/etcd-live-http-to-https-migration.md
os/generate-self-signed-certificates.md

reading through the `Generate self-signed certificates` documentation, the concept of `client-server` certificates was clear after thinking about it for a while, but got easier to grasp and more consistent once I've replaced `client-server` by `peer` in my mind. As the concept `peer` is used throughout `etcd` already, I suggest adopting it here, too.

harmonize client/server/peer concept naming

---

os/iscsi.md

Supersedes #792 
In addition to the original docs I added a short contextual sentence about iSCSI.
As noted in the original PR there are a few improvements that can be made still be made such as:
@robszumski: 
> @joshix Brainstorming some steps to polish:
> - Background
>   - add some general background on how iscsi works, just a sentence or two. It's a block device, etc.
> - Credentials section has examples for global and per-mount
>   - manual examples
>   - cloud-configs (enables iscsid)
> - Expand on the "find available targets"
>   - "You may want to manually search first, then add to a cloud-config..."
> - Mounting instructions
>   - doc has a specific iSCSI example (currently is lacking)
>   - full cloud-config
>   - possibly add a kubernetes example? …

iSCSI Docs (First Iteration)

---

os/adding-swap.md

@philips made a request in #52 for this document.
I'm sure this lacking some necessary details, but here's a first pass.
The original issue mentions some things that might be nice to have:
I'd love to know if we think those are necessary.
_Tested on CoreOS using Vagrant.  Created an ext4 formatted loop device and mounted that on `/media/state` to ensure the explanation worked. Out of the box `/media` is of type `tmpfs` which doesn't allow for swapfiles._
@joshix, @crawford Feedback welcome.
Fixes #52

os: Added `adding-swap` guide.

---

os/configuring-dns.md

The plugin for NSS built by systemd is called libnss_resolv**e** and not libnss_resolv, so this configuration should not work.
I haven't checked if in older systemd releases it was called 'resolv' though.

os: dns: fix systemd's nss lib name

---

quay-enterprise/clair.md

Outline how clair-jwt container can trust self-signed QE registry.
/cc: @josephschorr , @eddieesquivel

Docs: Clair trust to Self-signed QE

---

quay-enterprise/quay-enterprise-2.md

In the upgrade doc, anyone running QE less than 2.0.0 must begin with 2.0.0.
(Corrects an overzealous `sed`.)

quay-enterprise/q-e-2.md: Correct version for upgrade to v2 to plain 2.0.0

---

quay-enterprise/initial-setup.md

Updates setup document to use latest quay enterprise release. `v2.0.3` includes several bug fixes. We've received a high number of tickets that are due to this doc being tagged at `v2.0.1`

quay-enterprise: update initial-setup.md to most recent release

---

quay-enterprise/tectonic/files/quay-servicetoken-role-binding-k8s1-4.yaml
quay-enterprise/tectonic/files/quay-servicetoken-role-binding.yaml
quay-enterprise/tectonic/files/quay-servicetoken-role.yaml
quay-enterprise/tectonic/index.md

Adds manifests for Tectonic Role Based Access Controls based on Kubernetes 1.4 and 1.5 RBAC specs. 
Fixes: https://github.com/coreos/docs/issues/948

Updates for Tectonic v1.4 and v1.5 RBAC

---

os/customizing-docker.md
os/update-strategies.md

We have docs for setting proxy env vars as dropins, but it would be helpful to link to how to set them system-wide

os: link to setting system-wide env vars

---

os/booting-with-pxe.md

os/booting-with-pxe.md line 186: I removed the ellipses and newline so the https://coreos.com/os/docs/latest/booting-with-pxe.html generated from this would render the initrd example textbox properly. With the ellipses (or maybe it was the newline) the kernel and initrd lines were joined together into a single line in my browser.

Removed ellipses to improve formatting

---

os/manual-rollbacks.md

The instructions made assumptions that are not true when running with
dm-verity.
This updates the instructions to something much more verbose, but that
works for systems with or without dm-verity
See https://github.com/coreos/bugs/issues/1718
@crawford

os/rollback: update instructions for dm-verity

---

quay-enterprise/tectonic/index.md

Looks like I had a type/bad link in https://github.com/coreos/docs/pull/953 , this PR fixes it

Fix bad link to Quay Service Token

---

etcd/getting-started-with-etcd.md

Fixes issue on etcd-dev, where etcd 2.x no longer requires curl to follow redirects, since these are handled internally by etcd.
cc: @joshix @ElijahCaine

etcd: remove language about redirects

---

os/booting-with-iso.md

Describe its effects without discussing how to enable it.

os/booting-with-iso: coreos.autologin is the default

---

etcd/getting-started-with-etcd.md

It was brought to our attention that it's not really clear [if/how etcd3 is installed on Container Linux](https://twitter.com/rosstimson/status/832553674677313536). It's best used via a wrapper script and service. This outlines how to manually and automatically (with ignition) use and enable that service.
Feedback welcome.

etcd: clarify installation process

---

quay-enterprise/build-support.md

Add example of builders support for connecting Quay Enterprise signed by custom CA
Tested as below:

Docs: Quay Builders support with custom signed CA

---

os/booting-on-vmware.md

Fixes https://github.com/coreos/docs/issues/1004.

os: fix clc typo in vmware example

---

os/booting-on-packet.md

The Packet OEM went stable in 766.3.0.

os/booting-on-packet: Drop warning about supported channels

---

os/adding-users.md

Additionally, this shows how multiple users can be configured.
Fixes https://github.com/coreos/bugs/issues/1846.

os: update users guide to use clc 

---

os/booting-on-google-compute-engine.md

Fix the Google Compute Engine ignition config to use the correct metadata
environment variable. COREOS_GCE_IPV4_LOCAL_0 should be
COREOS_GCE_IP_LOCAL_0.

os/booting-on-gce: Fix environment variable name

---

flannel/flannel-config.md

Add a section on setting ETCD_SSL_DIR variable. ref: https://github.com/coreos/bugs/issues/1775#issuecomment-283243950

docs/flannel/flannel-config.md: add a new section on setting ETCD_SSL_DIR variable

---

os/booting-on-ec2.md

CommonMark doesn't allow code fences to be indented more than three spaces. This was breaking everything on the page starting from "Launching a test cluster". Also improve wording slightly and introduce the CL config before showing it.

os/booting-on-ec2: Unbreak page and slightly improve discussion of userdata

---

os/kernel-modules.md

I noticed that as of 1353.4.0 (maybe earlier) the lib-modules.mount
unit was no longer started on boot. Checking `systemctl status
local-fs.target` returned:
```
local-fs.target: Wants dependency dropin
/etc/systemd/system/local-fs.target.wants/lib-modules.mount is not a
symlink, ignoring.
```
To fix this, we can create the file in /etc/systemd/system and then
enable it to create the symlink. I tested this on my machines and found
it to work.

os/kernel-modules: fix mounting of overlay

---

os/booting-on-virtualbox.md

The documentation for installing CoreOS on VirtualBox reads like this:
_I recommend to use the built image as base image._
My fix just corrects the **to use** portion:
_I recommend using the built image as base image._

Fixed grammer issue in VirtualBox booting docs

---

etcd/getting-started-with-etcd.md

It changed in docker 1.9 to 172.17.0.1.  See eg. docker/docker#17305

etcd/getting-started: 172.17.42.1 is no longer the default docker host

---

os/booting-on-ec2.md

This looks like it was leftover from testing how markdown handled
indented code blocks.

os: remove extra clcs

---

coreupdate/configure-machines.md
etcd/etcd-live-cluster-reconfiguration.md
etcd/getting-started-with-etcd.md
fleet/launching-containers-fleet.md
os/booting-on-azure.md
os/booting-on-digitalocean.md
os/booting-on-ec2.md
os/booting-on-ecs.md
os/booting-on-google-compute-engine.md
os/booting-on-openstack.md
os/booting-on-packet.md
os/booting-on-vmware.md
os/booting-with-ipxe.md
os/booting-with-pxe.md
os/booting-with-qemu.md
os/cluster-discovery.md
os/configuring-date-and-timezone.md
os/configuring-dns.md
os/customizing-docker.md
os/customizing-sshd.md
os/installing-to-disk.md
os/iscsi.md
os/network-config-with-networkd.md
os/power-management.md
os/quickstart.md
os/reading-the-system-log.md
os/registry-authentication.md
os/using-environment-variables-in-systemd-units.md
quay-enterprise/configure-machines.md

The new provisioning document is a better landing page for readers who
wish to know more about Container Linux Configs than the getting started
document for ct, so this commit changes all links to the latter to point
to the former.

*: change links from ct's getting started page to os/provisioning.md

---

os/migrating-to-clcs.md

This commit adds a document detailing how to convert each section in a
cloud config to an equivalent Container Linux Config.

os: added migrating-to-clcs.md

---

quay-enterprise/build-support.md
quay-enterprise/initial-setup.md
quay-enterprise/insert-custom-cert.md
quay-enterprise/tectonic/files/quay-enterprise-app-rc.yml

Quay just got an update.
This updates the image tags appropriately.

quay: update v2.2.0 -> v2.3.0 image tags

---

os/migrating-to-clcs.md

The "Getting Started" doc isn't synced to the website since it isn't as
good of a reference as the provisioning docs.

os: update link in migrating guide

---

os/provisioning.md

"The defining feature of the Container Linux Config is that **it**".

Fix small typo - docs provisioning

---

os/booting-on-ec2.md

For the new cn-north-1 region, the default console link is wrong.

os/ec2: update link for china console

---

coreupdate/on-premises-deployment.md

1) Change UPSTREAM_SYNC_INTERVAL so that if users copy and paste the config coreupdate will sync automatically with upstream
2) Add section on creating CoreOS ARM application (required when migrating/updating to 2.1.1)
3) Add section on syncing with public CoreUpdate

coreupdate: add section on syncing packages to on-premises-deployment.md

---

quay-enterprise/insert-custom-cert.md

Adds a section to the Adding TLS Certificates to the Quay Enterprise Container about adding certs when QE is deployed on k8s.

qe: update insert-custom-cert.md with k8s work around

---

os/booting-on-azure.md

The current Azure CLI doesn't support the classic deployment model. Drop obsolete exposition, as well as command-line arguments with reasonable defaults.

os/booting-on-azure: Update for ARM deployment model and Azure CLI 2.0

---

os/booting-on-openstack.md

Right now coreos-metadata doesn't support fetching ssh keys via the
config drive. Until this is added the example should include setting an
ssh key for the core user.

os: add ssh key to example config

---

os/configuring-date-and-timezone.md

@crawford Apparently you wrote this example; did it ever work?  I don't see any man pages reference `/etc/timezone`.  It was reported broken in coreos/bugs#1957, and there is already another example for doing this at https://coreos.com/os/docs/latest/cloud-config-examples.html#time .

os/configuring-date-and-timezone: drop broken example

---

os/booting-with-ipxe.md
os/booting-with-pxe.md

This commit adds text mentioning the supported url schemas (http(s) and
tftp) to the pxe and ipxe booting guides.
Prompted by ignition getting tftp support: https://github.com/coreos/ignition/pull/353
Should probably not be merged until the next Ignition release.

os/booting-with{i,]pxe.md: mention supported schemas

---

os/kernel-modules.md

The subkey expired, so only reference the primary.

os/kernel-modules: fetch the primary key

---

os/cluster-architectures.md

Syntax errors from #1045 are breaking the coreos-pages jobs.

os/cluster-architectures: fix invalid YAML

---

os/booting-with-ipxe.md
os/booting-with-pxe.md

We're rolling back to Ignition 0.14.0 for 1423.
This reverts #1076.

Revert "os/booting-with{i,]pxe.md: mention supported schemas"

---

quay-enterprise/tectonic/files/quay-servicetoken-role-binding-k8s1-6.yaml
quay-enterprise/tectonic/files/quay-servicetoken-role-k8s1-6.yaml
quay-enterprise/tectonic/index.md

Updated documentation for QE on Tectonic 1.6
Tectonic 1.5 manifests works if kubectl version 1.6 is used. During this `kubectl` seem to transform `apiVersion: rbac.authorization.k8s.io/v1alpha1` to `apiVersion: rbac.authorization.k8s.io/v1beta1` . 
Created 1.6 specific manifests for cases where user may not be using kubectl or an older version of kubectl.

Quay Enterprise: RBAC on tectonic documentation for 1.6

---

os/booting-with-libvirt.md

virt-install's parameter --network don't support any "type=bridge" argument, removing it makes the vm boot.

booting-with-libvirt.md: Removed invalid argument

---

kubernetes/services.md

services.md: Fix simple typo
Replace the word 'maching' with the correct spelling 'matching'

services.md: Fix simple typo

---

os/booting-with-ipxe.md

Otherwise `coreos.config.url` will be ignored.

os/booting-with-ipxe: Add "coreos.first_boot=1" to example scripts

---

os/booting-with-ipxe.md
os/booting-with-pxe.md

We'll need this when Ignition &ge; 0.15.0 has re-merged to master.  **Do not merge** until then.
This reverts #1086.

Revert "Revert "os/booting-with{i,]pxe.md: mention supported schemas""

---

os/mounting-storage.md

rpc-statd.service has no `Install` section, so the `enable` directive doesn't do anything. mount.nfs(8) automatically starts rpc.statd if required.
Partially addresses https://github.com/coreos/bugs/issues/2038.

os/mounting-storage: Drop unnecessary enablement of rpc.statd

---

flannel/flannel-config.md

Simply specifying "flannel:" will result in nothing being generated,
as it is just ignored. Using "flannel: ~" sets flannel to null and
correctly generates a base flannel ignition config

flannel: set empty flannel equal to null (~)

---

quay-enterprise/clair.md
quay-enterprise/configure-syslog-ng.md

adds a doc that describes the process to redirect quay-enterprise logs to stdout.
edit to clair.md to reflect how the CA cert must be passed when using a self-signed cert

quay-enterprise: syslog-ng configuration and clair edit 

---

os/booting-with-ipxe.md
os/booting-with-pxe.md

Ignition configs can now be fetched over s3. This commit adds mention
of that to the ipxe and pxe docs for the OS.
Fixes https://github.com/coreos/bugs/issues/2067

os/booting-with-{ipxe,pxe}: document support for s3

---

os/kernel-modules.md

This has been automated in the `emerge-gitclone` command, since all recent releases now have overlay branches created at tag time.

os/kernel-modules: drop the branch checkout step

---

os/booting-with-libvirt.md

os/booting-with-libvirt: fix CLC syntax errors

---

etcd/etcd-live-cluster-reconfiguration.md
etcd/etcd-live-http-to-https-migration.md

/etcd/etcd-live*: deprecate etcd2 and etcd
Ref: https://github.com/coreos/bugs/issues/1877

etcd/etcd-live-*: replace etcd2 with etcd-member.service

---

os/adding-users.md

The usage originally in this doc didn't actually add ssh keys for a user, it just syncs `authorized_keys.d` to  the `authorized_keys` file (https://github.com/coreos/init/blob/9008a3d0457d7e0a303fbee9610723b1c5a66cf2/bin/update-ssh-keys#L27). Adding the `-a NAME` flag does actually add the ssh key as described.

os: fixed update-ssh-keys usage

---

os/sdk-tips-and-tricks.md

Document that aborting a build can corrupt ccache.
Document that aborting build_image can leave lockfiles.

os/sdk-tips-and-tricks: document misc errors

---

quay-enterprise/geo-replication.md

Altered the "*Note:" at the end of the document to use the same terminology as the Quay Enterprise Superuser panel. That panel refers to the defined storage options as "Location IDs".

Fixed wording in geo-replication.md

---

os/booting-with-ipxe.md
os/booting-with-iso.md
os/booting-with-pxe.md

1 GiB is no longer sufficient now that there are multiple docker packages in the image. We don't actually need the full 2 GiB, but use round numbers.

os/booting-with-{pxe,ipxe,iso}: increase minimum RAM

---

ignition/what-is-ignition.md

State that Ignition runs only on the first boot (as opposed to once per boot).
This confused someone: https://github.com/coreos/bugs/issues/2169#issuecomment-332183254

ignition/what-is-ignition: clarify "Ignition only runs once"

---

ignition/metadata.md
ignition/network-configuration.md
os/booting-on-vmware.md
os/provisioning.md

vmware-use-guestinfo is now a broken link (404).
labrie-guestinfo details how to use the cloudinit-specific variables.

os: remove mention of blog posts in vmware docs

---

quay-enterprise/build-support.md

This command change is required as the current command does not properly load the self-signed certificate into the builder. Also removed an 's' to provide an example of connecting to a reg not protected by ssl.

qe: fix quay-builder ssl cert command

---

os/booting-on-vagrant.md

Change "it's" to "its" to indicate posession.

os/booting-on-vagrant: Fix typo

---

quay-enterprise/quay-github.md

This page may no longer be necessary. Just knocking it out in case.

docs: add working with github landing page

---

os/sdk-building-production-images.md
os/sdk-modifying-coreos.md

The "option 2" section of the sdk instructions is apparently obsolete. cc @euank

os/sdk-modifying-coreos: removed repo and cros_sdk instructions

---

os/booting-on-virtualbox.md

Made changes to the Virtualbox instructions because there were many syntactical and grammatical errors. Fixed those up and also changed a few first-person pronoun references.

booting-on-virtualbox: Fixed syntax and grammar errors

---

os/booting-on-digitalocean.md

It's never really served a purpose, and other docs pages generally hardcode channel names.
No change to the rendered content is intended.

os/booting-on-digitalocean: drop do-image-path Jekyll variable

---

os/community-platforms.md

It's not clear where "VMware vSphere Integrated Containers" came from. The linked page covers VMware Workstation, Fusion, and ESXi.

os/community-platforms: retitle VMware link

---

os/installing-to-disk.md

Link to the CT overview doc, not the GitHub docs directory.

os/installing-to-disk: improve CT link

---

os/sdk-disk-partitions.md

Partition 2 is not unused; it is used by grub when booting from bios. Update the docs to reflect that.

os/sdk-disk-partitions: correct partition 2 info

---

os/sdk-modifying-coreos.md

`cork` uses it as part of `cork create`.

Add `bzip2` requirement to instructions

---

os/sdk-modifying-coreos.md

Add gpg. Drop python2 now that we only support cork.

os/sdk-modifying-coreos: update system requirements

---

quay-enterprise/custom-cert-kube-apps.md
quay-enterprise/high-availability.md
quay-enterprise/quay-ssl.md
quay-enterprise/upgrade-quay-enterprise.md
quay-enterprise/upgrade-quay.md

The local resources can be referenced with a local path instead of a
tectonic.com URL.

quay: clean up links to reference local resources

---

os/sdk-disk-partitions.md

This fixes the instructions describing how to purge all OS state.
It also avoid using the "factory reset" term, as the initial rootfs
partition we ship as of now is not completely empty.
Fixes https://github.com/coreos/bugs/issues/2370

os/disk: fix instructions for OS state removal

---

quay-enterprise/tectonic/index.md

Verified v1.6.x Quay Enterprise RBAC policies work with 1.7.x and 1.8.x

Add 'and later' to show compatibility with current Tectonic versions

---

os/network-config-with-networkd.md

Without some DNS server, this static config won't allow a host to access much of anything. This config can be verified  [here](https://www.freedesktop.org/software/systemd/man/systemd.network.html#[Network]%20Section%20Options)

Add DNS configuration necessary for proper static config

---

os/sdk-disk-partitions.md

VFAT is not a filesystem type. We were incorrectly creating this filesystem as FAT16, but we've now switched to FAT32.
Addresses https://github.com/coreos/bugs/issues/2246#issuecomment-352568844.

os/sdk-disk-partitions: fix EFI-SYSTEM partition type

---

os/kernel-modules.md

Starting with systemd 238, mount units will fail if the mount point needs to follow symbolic links.  Since we have all of the lib dirs symlinked together, /lib/modules is really /usr/lib64/modules, and that makes this example mount unit fail to start.  The fstab generator normalizes paths before writing its mounts units, so that is a reliable alternative.
For coreos/bugs#2407

os/kernel-modules: Use /etc/fstab instead of mount units

---

os/sdk-tips-and-tricks.md

Add a section explaining how to use nightly binpkgs to speed up local
builds.

os/sdk-tip-and-tricks: document on nightly binpkgs

---

os/constants-and-ids.md
os/sdk-tips-and-tricks.md

This collects constants used by ContainerLinux into a dedicated page, expanding the list of all reserved IDs together with short explanations.

os/guid: document constants and ids

---

os/other-settings.md

The `ec2-compat`, `packet`, and `rackspace-onmetal` OEMs set `linux_append`, so we should be sure not to clobber the existing value.

os/other-settings: interpolate $linux_append when setting it

---

os/sdk-modifying-coreos.md

Removed the `dev` arg in Render the CoreOS Container Linux image section.
`./build_image dev` becomes `./build_image`
As suggested by @dgonyeo, dev image is unstable and not a recommended method.

build_image without dev

---

os/sdk-modifying-coreos.md

Verify mantle section is changed in the following ways:
1. gpg command works for older versions of gpg
2. expected output from `gpg --verify` is updated

GPG Command Amendment

---

etcd/etcd-live-cluster-reconfiguration.md

Mostly wrong IP addresses, also removing one stray element `node4` maybe from a too generous copy-and-paste.

Fix inconsistencies/typos in examples and text

---

flannel/flannel-config.md

The current documentation points to incorrect (old?) URL, some serious inconvenience for lazy people like me.

Fix flannel unit-file url

---

os/adding-swap.md

Make the systemd config include a mkswap statement for actually creating a swapfile in the first boot loader example. Without this, the .swap unit fails.

os: Update systemd config example to include mkswap

---

os/booting-on-ec2.md

The CloudFormation templates haven't been updated since March 2017, and they use cloudinit to configure etcd2 and fleet.  Drop them; if there's a critical need we can always update them and put them back.
For the record, the current templates are:
- [coreos-alpha-hvm.template](https://github.com/coreos/docs/files/2247655/coreos-alpha-hvm.template.txt)
- [coreos-alpha-pv.template](https://github.com/coreos/docs/files/2247656/coreos-alpha-pv.template.txt)
- [coreos-beta-hvm.template](https://github.com/coreos/docs/files/2247657/coreos-beta-hvm.template.txt)
- [coreos-beta-pv.template](https://github.com/coreos/docs/files/2247658/coreos-beta-pv.template.txt)
- [coreos-stable-hvm.template](https://github.com/coreos/docs/files/2247659/coreos-stable-hvm.template.txt)
- …

os/booting-on-ec2: drop CloudFormation

---

os/booting-on-ecs.md

Added the base config/rules for IAM Task Roles to match latest AWS documentation for other distributions.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#enable_task_iam_roles

os/booting-on-ecs: config to allow IAM Task Roles

---

os/customizing-sshd.md

A user noticed the docs imply this information will be given and then
don't give it.
Fixes https://github.com/coreos/docs/issues/1215

os/ssh: include info on editing sshd_config by cli

---

os/booting-with-ipxe.md
os/booting-with-pxe.md

This adds a quick link between PXE kernel parameters reference and
Ignition static networking docs, as the two are commonly coupled
and this makes the network configuration option easier to discover.

os: crosslink PXE parameters and ignition static-networking

---

os/sdk-modifying-coreos.md

We no longer support multiple arches and `setup_board` no longer requires arguments.

os/sdk-modifying-coreos: drop architecture setup

---

os/sdk-modifying-coreos.md

The bits aren't published yet, but will be soon.

os/sdk-modifying-coreos: bump mantle version to 0.12.0
